In [1]:
import torch


torch.manual_seed(0)



In [2]:
from torch import Tensor

def sigmoid(logits):
    counts=logits.exp()
    return counts/(counts.sum())

test = Tensor([0,3,220,11000])

print(test.exp())
print(test)

tensor([ 1.0000, 20.0855,     inf,     inf])
tensor([0.0000e+00, 3.0000e+00, 2.2000e+02, 1.1000e+04])


In [3]:


print(sigmoid(test))
print(sigmoid(test).sum())

print(torch.sigmoid(test))
print(torch.sigmoid(test).sum())




tensor([0., 0., nan, nan])
tensor(nan)
tensor([0.5000, 0.9526, 1.0000, 1.0000])
tensor(3.4526)


In [4]:


print(sigmoid(test))
print(sigmoid(test).sum())

print(torch.sigmoid(test))
print(torch.sigmoid(test).sum())




tensor([0., 0., nan, nan])
tensor(nan)
tensor([0.5000, 0.9526, 1.0000, 1.0000])
tensor(3.4526)
