In [1]:
import torch

my_tensor = torch.Tensor([[3,3,3,3],[10,10,10,10]])
my_tensor

tensor([[ 3.,  3.,  3.,  3.],
        [10., 10., 10., 10.]])

# SUM

In [2]:
my_tensor.sum(1,keepdim=True)

tensor([[12.],
        [40.]])

In [3]:
my_tensor.sum(1,keepdim=False)

tensor([12., 40.])

In [4]:
my_tensor.sum(0,keepdim=True)

tensor([[13., 13., 13., 13.]])

In [5]:
my_tensor/my_tensor.sum(1,keepdim=True)

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

# BUG SUM

In [6]:
my_tensor

tensor([[ 3.,  3.,  3.,  3.],
        [10., 10., 10., 10.]])

In [7]:
try:
    my_tensor/my_tensor.sum(1)
except Exception as e:
    print("ERROR!!!!")
    print(e)

ERROR!!!!
The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1


# ADDING 2 TENSORS AND POWERING

In [8]:
A = torch.tensor([[10,10,10],[10,10,10]])
B = torch.tensor([[5,5,5],[5,5,5]])

(A-B)**2

tensor([[25, 25, 25],
        [25, 25, 25]])

In [9]:
A[0,0]

tensor(10)

# GET MAXIMUM ELEMENT INDEX

In [20]:
A = torch.tensor([10,10,100]) 

maximum=A.amax()

for idx,item in enumerate(A):
    if item == maximum:
        print(item)
        print(idx)

tensor(100)
2


In [14]:
max_element.amax

<function Tensor.amax>

In [15]:
A.amax()

tensor(100)