In [2]:
import torch

my_tensor = torch.Tensor([[3,3,3,3],[10,10,10,10]])
my_tensor

tensor([[ 3.,  3.,  3.,  3.],
        [10., 10., 10., 10.]])

# SUM

In [3]:
my_tensor.sum(0,keepdim=True)

tensor([[13., 13., 13., 13.]])

In [4]:
my_tensor.sum(1,keepdim=True)

tensor([[12.],
        [40.]])

In [5]:
my_tensor.sum(1,keepdim=False)

tensor([12., 40.])

In [6]:
my_tensor.sum(0,keepdim=True)

tensor([[13., 13., 13., 13.]])

In [7]:
my_tensor/my_tensor.sum(0,keepdim=True)

tensor([[0.2308, 0.2308, 0.2308, 0.2308],
        [0.7692, 0.7692, 0.7692, 0.7692]])

In [8]:
my_tensor/my_tensor.sum(1,keepdim=True)

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

# BUG SUM

In [9]:
my_tensor

tensor([[ 3.,  3.,  3.,  3.],
        [10., 10., 10., 10.]])

In [10]:
my_tensor.sum(1)

tensor([12., 40.])

In [11]:
try:
    my_tensor/my_tensor.sum(1)
except Exception as e:
    print("ERROR!!!!")
    print(e)

ERROR!!!!
The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1


# SUBSTRACTING 2 TENSORS AND POWERING

In [12]:
A = torch.tensor([[10,10,10],[10,10,10]])
B = torch.tensor([[5,5,5],[5,5,5]])

(A-B)**2

tensor([[25, 25, 25],
        [25, 25, 25]])

In [13]:
A[0,0]

tensor(10)

# GET MAXIMUM ELEMENT INDEX

In [14]:
A = torch.tensor([10,10,100]) 

maximum=A.amax()

for idx,item in enumerate(A):
    if item == maximum:
        print(item)
        print(idx)

tensor(100)
2


# ARANGE

In [15]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# LINSPACE


In [16]:
lre = torch.linspace(-3,0,100)

lr = 10 ** lre

print(lr)



tensor([0.0010, 0.0011, 0.0011, 0.0012, 0.0013, 0.0014, 0.0015, 0.0016, 0.0017,
        0.0019, 0.0020, 0.0022, 0.0023, 0.0025, 0.0027, 0.0028, 0.0031, 0.0033,
        0.0035, 0.0038, 0.0040, 0.0043, 0.0046, 0.0050, 0.0053, 0.0057, 0.0061,
        0.0066, 0.0071, 0.0076, 0.0081, 0.0087, 0.0093, 0.0100, 0.0107, 0.0115,
        0.0123, 0.0132, 0.0142, 0.0152, 0.0163, 0.0175, 0.0187, 0.0201, 0.0215,
        0.0231, 0.0248, 0.0266, 0.0285, 0.0305, 0.0327, 0.0351, 0.0376, 0.0404,
        0.0433, 0.0464, 0.0498, 0.0534, 0.0572, 0.0614, 0.0658, 0.0705, 0.0756,
        0.0811, 0.0870, 0.0933, 0.1000, 0.1072, 0.1150, 0.1233, 0.1322, 0.1417,
        0.1520, 0.1630, 0.1748, 0.1874, 0.2009, 0.2154, 0.2310, 0.2477, 0.2656,
        0.2848, 0.3054, 0.3275, 0.3511, 0.3765, 0.4037, 0.4329, 0.4642, 0.4977,
        0.5337, 0.5722, 0.6136, 0.6579, 0.7055, 0.7565, 0.8111, 0.8697, 0.9326,
        1.0000])
