In [1]:
import numpy as np

In [2]:
input = np.matrix([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3],
])
input


matrix([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [3]:
input.dot([0.1, 0.1, 0.1])

matrix([[0.3, 0.6, 0.9]])

In [5]:
# Perform matrix multiplication
input.dot(np.matrix([[7, 8, 9], [7, 8, 9], [7, 8, 9]]))

matrix([[21, 24, 27],
        [42, 48, 54],
        [63, 72, 81]])